version: "3"
services:
#  pgdb:
#    image: postgres:latest
#    container_name: pgdb
#    ports:
#      - 5432:5432
#    environment:
#      - POSTGRES_DB=demopgdb
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=secret123

  
  zookeeper:
    image: confluentinc/cp-zookeeper:6.0.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - saga

  broker:
    image: confluentinc/cp-kafka:6.0.0
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    networks:
      - saga

  orderservice:
    image: arunkumarshahi/orderservice
    container_name: order
    depends_on:
#      - pgdb
      - broker
#    environment:
#      - SPRING_DATASOURCE_URL=r2dbc:postgresql://pgdb:5432/demopgdb
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=secret123
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 8080:8080
    networks:
      - saga

  paymentservice:
    image: arunkumarshahi/paymentservice
    container_name: paymentservice
    hostname: paymentservice
#    depends_on:
#      - pgdb
#      - broker 
#    environment:
#      - SPRING_DATASOURCE_URL=r2dbc:postgresql://pgdb:5432/demopgdb
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=secret123
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - saga1

  inventoryservice:
    image: arunkumarshahi/inventoryservice
    container_name: inventoryservice
    hostname: inventoryservice
#    depends_on:
#      - pgdb
#      - broker
#    environment:
#      - SPRING_DATASOURCE_URL=r2dbc:postgresql://pgdb:5432/demopgdb
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=secret123
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - saga1

  orchestrationservice:
    image: arunkumarshahi/orchestrationservice
    container_name: orchestration
    depends_on:
#      - pgdb
      - broker
      - inventoryservice
      - paymentservice
#    environment:
#      - SPRING_DATASOURCE_URL=r2dbc:postgresql://pgdb:5432/demopgdb
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=secret123
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - saga

networks:
  saga:
    name: custom_frontend
  saga1:
    name: custom_frontend1