version: "3"
services:
  db:
    image: postgres:latest
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=demodb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret123


  inventoryservice:
    image: arunkumarshahi/inventoryservice
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=r2dbc:postgresql://db:5432/demodb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=secret123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 8080:8080

  paymentservice:
    image: arunkumarshahi/paymentservice
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=r2dbc:postgresql://db:5432/demodb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=secret123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update